version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mongodb
      - neo4j
    volumes:
      - .:/app
    command: tail -f /dev/null

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    depends_on:
      - neo4j
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password

volumes:
  mongo_data:
  neo4j_data: